# Generated by Django 5.1 on 2024-08-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='image/')),
                ('about', models.TextField()),
                ('email', models.EmailField(max_length=100)),
                ('linkedin', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
