# Generated by Django 5.1 on 2024-08-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_info',
            name='facebook',
            field=models.URLField(max_length=50),
        ),
        migrations.AlterField(
            model_name='basic_info',
            name='github',
            field=models.URLField(max_length=50),
        ),
        migrations.AlterField(
            model_name='basic_info',
            name='linkedin',
            field=models.URLField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_repo_link',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
