# Generated by Django 5.1 on 2024-08-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image/github')),
                ('username', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=100)),
                ('joining_date', models.CharField(max_length=50)),
                ('repos', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('following', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
