# Generated by Django 5.1 on 2024-08-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_githubinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubinfo',
            name='bio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
