# Generated by Django 5.1 on 2024-08-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_githubinfo_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.AddField(
            model_name='skill',
            name='extra_class',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
