# Generated by Django 5.1 on 2024-08-31 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_skill_description_skill_extra_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='extra_class',
            new_name='color_code',
        ),
    ]
